### ISSUE TITLE
Missing Documentation for building

### ISSUE THREAD

**Issue by LukasSchulz** [hediet/slideo#2]
Today I tried to build this project because I am using MacOS and the opencv-linking seemed to be broken. 
using cargo was easy (even though I am not that familiar with rust but finding out that the page needed to be built using yarn was quite something.

Some building documentation would be nice. (Some lines on where to use `cargo build` and `yarn install` && `yarn build`).

**Comment by hediet** [comment]
Hi,

have a look at [`ci.yml`](https://github.com/hediet/slideo/blob/master/.github/workflows/ci.yml#L45), it lists all steps (you can ignore the cache steps).

> the opencv-linking seemed to be broken.

I feared that. Sadly, I have no clue how dynamic linking works on non-windows platforms.
If you have ideas on how I can link to OpenCV statically or how I can bundle OpenCV, we can try to fix the CI job!

**Comment by Omar-Elrefaei** [comment]
Yeah, I am getting
`./slideo: error while loading shared libraries: libopencv_cvv.so.4.5: cannot open shared object file: No such file or directory` even after I installed every relevant opencv package in Ubuntu 21.04.

I can see a ton of `libopencv_*.so.4.5` files, but no `cvv` one.

EDIT: Which is interesting because I can see no single `cvv` in your codebase.

**Comment by hediet** [comment]
Interesting. The linux CI build seems to work though, when run on the CI server itself.
If you know how to fix/improve that, please let me know!

**Comment by LukasSchulz** [comment]
> Yeah, I am getting
> `./slideo: error while loading shared libraries: libopencv_cvv.so.4.5: cannot open shared object file: No such file or directory` even after I installed every relevant opencv package in Ubuntu 21.04.
> 
> I can see a ton of `libopencv_*.so.4.5` files, but no `cvv` one.
> 
> EDIT: Which is interesting because I can see no single `cvv` in your codebase.

On debian I had to install opencv like this: https://github.com/twistedfall/opencv-rust/issues/35#issuecomment-817847653 to get the compilation working.
